### ISSUE TITLE
deprecated 10x Rkit package

### ISSUE THREAD

**Issue by victorlin45** [qinzhu/PIVOT#11]
10x no longer offers their Rkit package.  Is there still a way for me to get PIVOT to read .cloupe files? Thanks!

**Comment by eturkes** [comment]
That's right and 10x doesn't seem to distribute older versions. I did some searching around and I came across this: https://github.com/hb-gitified/cellrangerRkit

Try installing it from there and then loading your .cloupe file. Let us know if you have success. I'll try adding it to my Docker container later, let you know when that's ready to go.

Longer term, the dependency should be pretty simply replaced with something like Seurat. So the issue can be closed when that's done.

**Comment by victorlin45** [comment]
Thanks for you quick reply! I'll give the link a try and see how that works. Regarding Seurat, I know you guys have added some Seurat outputs in Pivot already. You guys are in the process of  incorporate even more/all Seurat features ?

**Comment by qinzhu** [comment]
For single cell data with large number of cells, I recommend using my recent package VisCello (https://github.com/qinzhu/VisCello.base) for interactive analysis & visualization. This package has several optimizations for large-scale single cell data and has similar features as Seurat. See https://cello.shinyapps.io/celegans/ for example.

**Comment by qinzhu** [comment]
I think the suggestion by @eturkes should fix the input problem for PIVOT. But this will only work for output by cellranger 2.x, as recent 3.x version used a completely new data structure. I'm little bit tied up this month but can take a look maybe next month. Still, for very large cell number (say >10k), I recommend using VisCello.base.

**Comment by eturkes** [comment]
@qinzhu oh that's cool, didn't know you had a Seurat alternative!

**Comment by qinzhu** [comment]
If you have trouble installing the cellrangerRkit you can just copy paste the source code in https://github.com/hb-gitified/cellrangerRkit/blob/master/scripts/rkit-install-2.0.0.R.
