### ISSUE TITLE
error

### ISSUE THREAD

**Issue by amitpande74** [qinzhu/PIVOT#17]
Hi,
I pulled PIVOT from Docker.
When I upload my gene count table it does not accept it and issues a warning:
Warning: The 'plotly_relayout' event tied a source ID of 'range_filter_plotly' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_relayout')` to the plot (`p`) that you wish to obtain event data from.
What is the wrong step I am doing here. Kindly inform.
regards.

**Comment by qinzhu** [comment]
Can you double check if your gene count table is same format as the example table (https://rawgit.com/qinzhu/PIVOT/master/inst/app/www/manual_file.html#46_load_example_dataset), and contains no NA values? 
You can ignore the plotly warning.

**Comment by amitpande74** [comment]
Hi @qinzhu ,
It is not very clear from the screenshot that you have provided in the link . A normal count matrix has gene names as rows and the columns have sample values. Can you kindly have a look at the file I have and whether this is correct as a input file or should it be wrangled further.
regards.


![example](https://user-images.githubusercontent.com/8874457/83861819-5fb9e880-a721-11ea-9ca4-151af338aa55.png)

**Comment by qinzhu** [comment]
The file looks correct. It looks like the data is already normalized so please make sure the Normalization method is selected as "none". Also please check if any of the entries contain no value. I also attached an example file here so you can compare. 

[Counts (normalized).csv.zip](https://github.com/qinzhu/PIVOT/files/4736545/Counts.normalized.csv.zip)

**Comment by amitpande74** [comment]
Same error. I tried uploading your file as well. Please specify input file and it stops.

**Comment by qinzhu** [comment]
There's something wrong with the latest shiny. I'm still investigating but I found the temporary solution is once you launch PIVOT, refresh the page, then load data. Sorry for the inconvenience.

**Comment by eturkes** [comment]
Hi @qinzhu I see you've been making commits to try to fix the issue. Please let me know when you're all done and I'll update the Docker image!

**Comment by qinzhu** [comment]
The bug can be fixed via installing previous version of shiny:
devtools::install_version("shiny", version = "1.3.0", repos = "http://cran.us.r-project.org") # Latest shiny 1.4.0 has bug in module reactivity
I've updated the install instruction. @eturkes Appreciate it! I think only the shiny version needs to be fixed.

**Comment by eturkes** [comment]
@qinzhu , great, an updated Docker image is now available with the previous version of shiny. Will be automatically pulled when using the command in the README.

**Comment by amitpande74** [comment]
@eturkes @qinzhu Thanks a lot for  looking into the problem.
@qinzhu there are still errors while I got while running the data:
Warning: Error in : 'plotQC' is not an exported object from 'namespace:scater'
  172: stop
  171: getExportedValue
  170: ::
  169: renderPlot
  167: func
  127: drawPlot
  113: <reactive:plotObj>
   97: drawReactive
   84: origRenderFunc
   83: output$scater_feature_plot
    3: shiny::runApp
    2: pivot_main
    1: pivot
Warning: Error in biomaRt::getBM: Invalid attribute(s): entrezgene 
Please use the function 'listAttributes' to get valid attribute names
  79: stop
  78: biomaRt::getBM
  74: observeEventHandler
   3: shiny::runApp
   2: pivot_main
   1: pivot
Kindly help.

**Comment by eturkes** [comment]
Docker image has been updated with the entrezgene fix.
