### ISSUE TITLE
rendering of some plot doesn't work 

### ISSUE THREAD

**Issue by aurelBZH** [qinzhu/PIVOT#3]
Hi Quin, 
Thanks for the quick response to my previous issue. unfortunately i have another another one.  
with my data and also with the example data some plot aren't rendering. I think a library doesn't work properly. I past you the content of the R console if it help you.  
`Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "29b4e0674d"; Shiny doesn't use them
No trace type specified:
  Based on info supplied, a 'scatter3d' trace seems appropriate.
  Read more about this trace type -> https://plot.ly/r/reference/#scatter3d
Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "29b42c9ce2da"; Shiny doesn't use them
No trace type specified:
  Based on info supplied, a 'scatter3d' trace seems appropriate.
  Read more about this trace type -> https://plot.ly/r/reference/#scatter3d
No scatter3d mode specifed:
  Setting the mode to markers
  Read more about this attribute -> https://plot.ly/r/reference/#scatter-mode
Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "29b4478341da"; Shiny doesn't use them
Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "29b43e2027ea"; Shiny doesn't use them
Warning in origRenderFunc() :
  Ignoring explicitly provided widget ID "29b4163c07a7"; Shiny doesn't use them
Warning in RColorBrewer::brewer.pal(N, "Set2") :
  minimal value for n is 3, returning requested palette with 3 different levels
`   
![expression_plot](https://user-images.githubusercontent.com/9987970/35102720-0478657e-fc64-11e7-9ebc-3beaf6a35846.png)

![](https://screenshotscdn.firefoxusercontent.com/images/0490c2a9-1181-4696-b1d8-b78cf121bcb2.png)

I have some warning at the launching of the application : 
 `1: replacing previous import ‘S4Vectors::first’ by ‘dplyr::first’ when loading ‘PIVOT’
2: replacing previous import ‘S4Vectors::intersect’ by ‘dplyr::intersect’ when loading ‘PIVOT’
3: replacing previous import ‘S4Vectors::setdiff’ by ‘dplyr::setdiff’ when loading ‘PIVOT’
4: replacing previous import ‘S4Vectors::setequal’ by ‘dplyr::setequal’ when loading ‘PIVOT’
5: replacing previous import ‘S4Vectors::union’ by ‘dplyr::union’ when loading ‘PIVOT’
6: replacing previous import ‘S4Vectors::rename’ by ‘dplyr::rename’ when loading ‘PIVOT’
7: replacing previous import ‘Biobase::combine’ by ‘dplyr::combine’ when loading ‘PIVOT’
8: replacing previous import ‘dplyr::union’ by ‘igraph::union’ when loading ‘PIVOT’
9: replacing previous import ‘dplyr::as_data_frame’ by ‘igraph::as_data_frame’ when loading ‘PIVOT’
10: replacing previous import ‘dplyr::groups’ by ‘igraph::groups’ when loading ‘PIVOT’
11: replacing previous import ‘igraph::groups’ by ‘plotly::groups’ when loading ‘PIVOT’
12: replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘PIVOT’
13: replacing previous import ‘DT::dataTableOutput’ by ‘shiny::dataTableOutput’ when loading ‘PIVOT’
14: replacing previous import ‘DT::renderDataTable’ by ‘shiny::renderDataTable’ when loading ‘PIVOT’
15: replacing previous import ‘igraph::as_data_frame’ by ‘tibble::as_data_frame’ when loading ‘PIVOT’`

May be a problem of compatibility between plotly and ggplot2 ?

**Comment by qinzhu** [comment]
Did u try clicking a gene in the table? For the second plot, it only works when the selected column is not sample. Could u try change that to group? It is meant to show a pie chart representing the e.g. cell type composition.

**Comment by aurelBZH** [comment]
The second one work but the  Expression Plot don't render.

**Comment by qinzhu** [comment]
Hmm, that's weird, as I can't reproduce the problem. Could you try update ggplot? The warnings seem fine and not related to this problem

![image](https://user-images.githubusercontent.com/10772232/35104946-63851156-fc38-11e7-85ee-f7cc465f8b1b.png)

**Comment by aurelBZH** [comment]
i have updated  ggplot2 and tested other things but the bug is already present

**Comment by qinzhu** [comment]
Not sure what caused this but I'll update the plotting module with some enhanced features later.

**Comment by aurelBZH** [comment]
I try to reinstall your application on a new virtual machine to see if i can reproduce the problem and i have the same problem.
I have created a virtual machine with ubuntu 16.4 64 bit
installed R 3.4.3 ( rbase and r base dev )
installed rstudio 
installed  libcurl4-openssl-dev, libxml2-dev, libxt-dev, libcairo2-dev, libmariadb-client-lgpl-dev, libssl-dev
and do the the installation of the bioconductor lib as said in the manual 
after the installation of pivot from github , Pivot work but the expression plot don't render.

**Comment by qinzhu** [comment]
Thanks for the info! May I ask what system you original run PIVOT on? Is it also Linux?

**Comment by aurelBZH** [comment]
yes linux mint

**Comment by qinzhu** [comment]
Thanks, maybe some of my later updates broke the plotting in Linux. I'll run a thorough test.
