### ISSUE TITLE
Can't install PIVOT

### ISSUE THREAD

**Issue by lida-R** [qinzhu/PIVOT#4]
Hello, 
I'm new in R and RNA-Seq analysis. 
Your application seems very interesting to me and so close to what I would like to do.
Thank you for sharing that.
Actually I tried to install based on your manual but got below error:

install_github("qinzhu/PIVOT/")
Error in parse_git_repo(repo) : Invalid git repo: qinzhu/PIVOT/
I installed and updated everything but still get the error. May I know what the reason is?

**Comment by qinzhu** [comment]
Hi,
I also tried with my R and find the same problem. Very weird. But I somehow solved this problem by updating devtools, as shown below. Could you try the same command and see if it works?
![image](https://user-images.githubusercontent.com/10772232/35397930-bfc0871c-01be-11e8-907e-8c64bee2f870.png)

**Comment by lida-R** [comment]
Thank you for your reply.
I tried the same command and still get the same error:
> install.packages("devtools")
Installing package into ‘C:/Users/azeighami/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.4.zip'
Content type 'application/zip' length 443915 bytes (433 KB)
downloaded 433 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\azeighami\AppData\Local\Temp\RtmpyawLhX\downloaded_packages
> library("devtools")
> install_github("qinzhu/PIVOT/")
Error in parse_git_repo(repo) : Invalid git repo: qinzhu/PIVOT/

**Comment by qinzhu** [comment]
I recently updated PIVOT and tested installation on both macOS and Linux. Seems installation works fine. The recent update may have fixed your problem.
