### ISSUE TITLE
Add a devel branch

### ISSUE THREAD

**Issue by eturkes** [qinzhu/PIVOT#9]
I'd like to contribute some code/fixes I put together while using your package. However, as they are not extensively tested, I think it would be more appropriate to put them in a devel branch, as the current install instructions pull directly from master. Since it is not possible for the person making the pull request to make new branches, this must be done by you. An alternative would be to point the installation instructions to a specific tag/release/branch. Whatever you think think would be good to make the package more friendly to community development while avoiding breaking the package for users. Thanks!

**Comment by qinzhu** [comment]
Dev branch added. Thanks a lot for the contribution and suggestions!
